### ISSUE TITLE
rbelgium

### ISSUE THREAD

**Issue by jwijffels** [cregouby/R-toulouse-tabnet#1]
hi @cregouby ,
I would love to hear this talk. Would you be interested in showing it at an online RBelgium meetup https://www.meetup.com/RBelgium/  
We started again after a long covid break.

**Comment by cregouby** [comment]
Hi @jwijffels 
I would be very glad to do it !
You may have a preview soon as it will be released on youtube...

**Comment by jwijffels** [comment]
Great!
We would like to plan a session in January / February for 1 hour through an online channel (probably Zoom), preferably on Tue/Wednesday/Thursday from 19h-20h. 
Do you have any preferences regarding date?

**Comment by cregouby** [comment]
Any Thursday at 19h fits perfectly for me.
